# Generated by Django 4.0.3 on 2022-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
